[project]
name = "nexus-hello"
version = "0.0.0"
description = "Sample project demonstrating Nexus framework usage and features"
authors = [{ name = "ECCO Data & AI", email = "esdsupport@ecco.com" }]
requires-python = ">=3.11,<3.16"
readme = "README.md"
license = "Apache-2.0"
maintainers = [{ name = "ECCO Data & AI", email = "esdsupport@ecco.com" }]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "adapta[aws, datadog]>=4,<5",
    "nexus-client-sdk>=1.7,<2",
]

[project.urls]
Repository = "https://github.com/SneaksAndData/nexus-hello"

[dependency-groups]
dev = [
    "pytest>=9,<10",
    "pytest-mock>=3.6.1,<4",
    "pytest-cov>=3,<4",
    "locust>=2.14.2,<3",
    "pytest-timeout>=2.1.0,<3",
    "pytest-asyncio>=1,<2",
    "ruff>=0.16.5",
]

[tool.uv]
default-groups = "all"

[tool.ruff]
src = ["src"]
exclude = [".venv", "examples"]
target-version = "py311"
line-length = 120
extend-exclude = ['tests/data/.*']

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
