dynaconf_merge = true

[runtime]

algorithm = " nexus_hello.hello_algorithm.HelloAlgorithm"

log_enrichment_function = "nexus_hello.main.enrich_logger_from_payload"

log_tagging_function = "nexus_hello.main.logger_tags_from_payload"

metric_tagging_function = "nexus_hello.main.metric_tags_from_payload"


[runtime.payload]

serialization_mode = "off"

type_name = "nexus_hello.models.payload.HelloData"

# ADDITIONAL SERVICES
[services]
    # Query Enabled Stores
    [query_enabled_store]

    enabled = "0"

[hello_settings]
hello_str = "Configuration String"
hello_num = 1234567890